// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyAPI.Models;

namespace PolicyAPI.Migrations
{
    [DbContext(typeof(PolicyContext))]
    [Migration("20220319184406_PolicyDB")]
    partial class PolicyDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PolicyAPI.Models.ConsumerPolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PolicyMasterId")
                        .HasColumnType("int");

                    b.Property<string>("PolicyStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("QuoteValue")
                        .HasColumnType("int");

                    b.HasKey("PolicyId");

                    b.HasIndex("PolicyMasterId");

                    b.ToTable("consumerPolicies");
                });

            modelBuilder.Entity("PolicyAPI.Models.PolicyMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AssuredSum")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusinessValue")
                        .HasColumnType("int");

                    b.Property<string>("ConsumerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlolicyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyValue")
                        .HasColumnType("int");

                    b.Property<int>("Tenure")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("policies");
                });

            modelBuilder.Entity("PolicyAPI.Models.ConsumerPolicy", b =>
                {
                    b.HasOne("PolicyAPI.Models.PolicyMaster", null)
                        .WithMany("consumerpolicies")
                        .HasForeignKey("PolicyMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolicyAPI.Models.PolicyMaster", b =>
                {
                    b.Navigation("consumerpolicies");
                });
#pragma warning restore 612, 618
        }
    }
}
